tag-template: codingstyle-$NEXT_PATCH_VERSION
name-template: Codingstyle $NEXT_PATCH_VERSION 🎁

version-template: $MAJOR.$MINOR.$PATCH

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features
    labels:
      - enhancement
      - feature
  - title: ✨ Improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 📝 Documentation updates
    label: documentation
  - title: 📦 Dependency updates
    label: dependencies
  - title: 🔧 Internal changes
    label: internal
  - title: 🚦 Tests
    labels:
      - test
      - tests

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

template: |
  # Changelog

  $CHANGES
